version: '2'
services:
  db:
    image: postgres
  app:
    build: .
    command: bundle exec rails s -p 8010 -b '0.0.0.0'
    volumes:
      - .:/post
    ports:
      - "8010:8010"
    depends_on:
      - db
