picstory-lb:
  scale: 1
  lb_config:
    certs: []
    port_rules:
    - priority: 1
      protocol: http  
      service: frontend/front-app
      source_port: 80
      target_port: 4200
  health_check:
    response_timeout: 2000
    healthy_threshold: 2
    port: 42
    unhealthy_threshold: 3
    interval: 2000