version: '2'

services:

  userms1:
    # build: .
    image: arqsoftpicstory/userms
    container_name: userms1
    ports:
      - 8005:8005
    links:
      - userdb1:userdb
    depends_on:
      - userdb1
    labels:
      io.rancher.scheduler.affinity:host_label: userms1=true

  userdb1:
    # build: ./db
    image: arqsoftpicstory/userdb
    container_name: userdb1
    ports:
      - 27017:27017
    labels:
      io.rancher.scheduler.affinity:host_label: userms1=true

  userms2:
    # build: .
    image: arqsoftpicstory/userms
    container_name: userms2
    ports:
      - 8005:8005
    links:
      - userdb2:userdb
    depends_on:
      - userdb2
    labels:
      io.rancher.scheduler.affinity:host_label: userms2=true

  userdb2:
    # build: ./db
    image: arqsoftpicstory/userdb
    container_name: userdb2
    ports:
      - 27017:27017
    labels:
      io.rancher.scheduler.affinity:host_label: userms2=true
