version: '3'

services:

  userms:
    build: .
    image: userms
    container_name: userms
    ports:
      - 8005:8005
    links:
      - userdb
    networks:
      - back-tier

  userdb:
    build: ./db
    image: userdb
    container_name: userdb
    ports:
      - 27017:27017
    networks:
      - back-tier

networks:
  back-tier:
